[project]
name = "theopetra-reat"

[contracts.theopetra-reat-vrf]
path = "contracts/clarinet/theopetra-reat-vrf.clar"
depends_on = []

[contracts.theopetra-reat-core-trait]
path = "contracts/clarinet/theopetra-reat-core-trait.clar"
depends_on = []

[contracts.theopetra-reat-token-trait]
path = "contracts/clarinet/theopetra-reat-token-trait.clar"
depends_on = []

[contracts.theopetra-reat-auth]
path = "contracts/clarinet/theopetra-reat-auth.clar"
depends_on = ["theopetra-reat-core-trait", "theopetra-reat-token-trait"]

[contracts.theopetra-reat-token]
path = "contracts/clarinet/theopetra-reat-token.clar"
depends_on = ["sip-010-trait", "theopetra-reat-auth", "theopetra-reat-token-trait"]

[contracts.theopetra-reat-core-v1]
path = "contracts/clarinet/theopetra-reat-core-v1.clar"
depends_on = ["theopetra-reat-auth", "theopetra-reat-token", "theopetra-reat-vrf", "theopetra-reat-core-trait"]

[contracts.theopetra-reat-core-v2]
path = "contracts/clarinet/theopetra-reat-core-v2.clar"
depends_on = ["theopetra-reat-auth", "theopetra-reat-token", "theopetra-reat-vrf", "theopetra-reat-core-trait"]

# contracts listed below are used only in testing

[contracts.sip-010-trait]
path = "contracts/clarinet/sip-10-ft-standard.clar"
depends_on = []

# contracts listed below are used only in test suite
[contracts.test-utils]
path = "contracts/clarinet/test-utils.clar"
depends_on = ["theopetra-reat-core-v1"]
